"""core schema

All 14 tables, their native enum types, and the retrieval indexes:
HNSW (vector_cosine_ops) on chunks.embedding and policy_clauses.embedding,
GIN on both tsvector columns. The tsv columns are Postgres generated columns,
so they stay consistent with `text` without a trigger to maintain.

Enum labels are the *values* declared in app/db/models/enums.py (via
values_callable), not the member names — the API contract and the ingestion
pipeline are defined in terms of those values.

Revision ID: 0002_core_schema
Revises: 0001_pgvector
Create Date: 2026-08-11
"""
from __future__ import annotations

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002_core_schema'
down_revision: Union[str, None] = '0001_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circulars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circular_number', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('vision_page_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circulars_checksum'), 'circulars', ['checksum'], unique=False)
    op.create_index(op.f('ix_circulars_circular_number'), 'circulars', ['circular_number'], unique=True)
    op.create_index(op.f('ix_circulars_department'), 'circulars', ['department'], unique=False)
    op.create_index(op.f('ix_circulars_doc_type'), 'circulars', ['doc_type'], unique=False)
    op.create_index(op.f('ix_circulars_issue_date'), 'circulars', ['issue_date'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('suite', sa.Enum('retrieval', 'extraction', 'groundedness', 'refusal', 'performance', name='eval_suite'), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.Enum('dense', 'lexical', 'hybrid', 'hybrid_rerank', name='retrieval_mode'), nullable=True),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_git_sha'), 'eval_runs', ['git_sha'], unique=False)
    op.create_index(op.f('ix_eval_runs_run_id'), 'eval_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_eval_runs_suite'), 'eval_runs', ['suite'], unique=False)
    op.create_index('ix_eval_runs_suite_started', 'eval_runs', ['suite', 'started_at'], unique=False)
    op.create_table('policy_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_policy_pack_name_version')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('circular_id', sa.Integer(), nullable=False),
    sa.Column('policy_pack_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CAPPED', name='assessment_status'), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_circular_id'), 'assessments', ['circular_id'], unique=False)
    op.create_index(op.f('ix_assessments_policy_pack_id'), 'assessments', ['policy_pack_id'], unique=False)
    op.create_index(op.f('ix_assessments_run_id'), 'assessments', ['run_id'], unique=True)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circular_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('paragraph_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.CheckConstraint('char_end > char_start', name='ck_chunk_span_ordered'),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_circular_id'), 'chunks', ['circular_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('subset', sa.String(length=32), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    op.create_index('ix_eval_results_metric', 'eval_results', ['eval_run_id', 'metric_name', 'subset'], unique=False)
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circular_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('para_number', sa.String(length=32), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.Enum('text', 'vision', name='extraction_method'), nullable=False),
    sa.Column('text_quality_score', sa.Float(), nullable=True),
    sa.CheckConstraint('char_end > char_start', name='ck_paragraph_span_ordered'),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paragraphs_circular_id'), 'paragraphs', ['circular_id'], unique=False)
    op.create_index('ix_paragraphs_circular_order', 'paragraphs', ['circular_id', 'order_index'], unique=False)
    op.create_table('policy_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_pack_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('clause_number', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.CheckConstraint('char_end > char_start', name='ck_clause_span_ordered'),
    sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_pack_id', 'clause_number', name='uq_clause_number_per_pack')
    )
    op.create_index('ix_policy_clauses_embedding_hnsw', 'policy_clauses', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_policy_clauses_policy_pack_id'), 'policy_clauses', ['policy_pack_id'], unique=False)
    op.create_index('ix_policy_clauses_tsv', 'policy_clauses', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('graph_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CAPPED', name='assessment_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_assessment_id'), 'agent_runs', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_circular_id', sa.Integer(), nullable=False),
    sa.Column('citing_paragraph_id', sa.Integer(), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('normalised_reference', sa.String(length=255), nullable=True),
    sa.Column('cited_circular_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_method', sa.Enum('regex', 'date', 'llm', 'unresolved', name='resolution_method'), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cited_circular_id'], ['circulars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citing_circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_paragraph_id'], ['paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_cited', 'citations', ['cited_circular_id', 'resolved'], unique=False)
    op.create_index(op.f('ix_citations_citing_circular_id'), 'citations', ['citing_circular_id'], unique=False)
    op.create_index(op.f('ix_citations_citing_paragraph_id'), 'citations', ['citing_paragraph_id'], unique=False)
    op.create_index(op.f('ix_citations_normalised_reference'), 'citations', ['normalised_reference'], unique=False)
    op.create_index(op.f('ix_citations_resolved'), 'citations', ['resolved'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circular_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=32), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_end > char_start', name='ck_obligation_span_ordered'),
    sa.ForeignKeyConstraint(['circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circular_id', 'char_start', 'char_end', name='uq_obligation_span')
    )
    op.create_index(op.f('ix_obligations_circular_id'), 'obligations', ['circular_id'], unique=False)
    op.create_index(op.f('ix_obligations_paragraph_id'), 'obligations', ['paragraph_id'], unique=False)
    op.create_table('supersessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superseding_circular_id', sa.Integer(), nullable=False),
    sa.Column('superseded_circular_id', sa.Integer(), nullable=True),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('evidence_paragraph_id', sa.Integer(), nullable=True),
    sa.Column('supersession_type', sa.Enum('supersedes', 'rescinds', 'amends', 'partial', name='supersession_type'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_paragraph_id'], ['paragraphs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_circular_id'], ['circulars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseding_circular_id'], ['circulars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supersessions_effective_date'), 'supersessions', ['effective_date'], unique=False)
    op.create_index(op.f('ix_supersessions_resolved'), 'supersessions', ['resolved'], unique=False)
    op.create_index('ix_supersessions_superseded', 'supersessions', ['superseded_circular_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_supersessions_superseded_circular_id'), 'supersessions', ['superseded_circular_id'], unique=False)
    op.create_index(op.f('ix_supersessions_superseding_circular_id'), 'supersessions', ['superseding_circular_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'OK', 'ERROR', name='step_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'seq', name='uq_agent_step_seq')
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_node'), 'agent_steps', ['node'], unique=False)
    op.create_index('ix_agent_steps_run_seq', 'agent_steps', ['agent_run_id', 'seq'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('policy_clause_id', sa.Integer(), nullable=True),
    sa.Column('impact_type', sa.Enum('NEW_REQUIREMENT', 'MODIFIED', 'CONFLICT', 'ALREADY_COVERED', 'NO_MATCH', name='impact_type'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('circular_span_start', sa.Integer(), nullable=True),
    sa.Column('circular_span_end', sa.Integer(), nullable=True),
    sa.Column('clause_span_start', sa.Integer(), nullable=True),
    sa.Column('clause_span_end', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('analyst_decision', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='analyst_decision'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_clause_id'], ['policy_clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_analyst_decision'), 'findings', ['analyst_decision'], unique=False)
    op.create_index(op.f('ix_findings_assessment_id'), 'findings', ['assessment_id'], unique=False)
    op.create_index('ix_findings_assessment_impact', 'findings', ['assessment_id', 'impact_type'], unique=False)
    op.create_index(op.f('ix_findings_impact_type'), 'findings', ['impact_type'], unique=False)
    op.create_index(op.f('ix_findings_obligation_id'), 'findings', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_findings_policy_clause_id'), 'findings', ['policy_clause_id'], unique=False)
    op.create_index(op.f('ix_findings_verified'), 'findings', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_verified'), table_name='findings')
    op.drop_index(op.f('ix_findings_policy_clause_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_obligation_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_impact_type'), table_name='findings')
    op.drop_index('ix_findings_assessment_impact', table_name='findings')
    op.drop_index(op.f('ix_findings_assessment_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_analyst_decision'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_agent_steps_run_seq', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_node'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_supersessions_superseding_circular_id'), table_name='supersessions')
    op.drop_index(op.f('ix_supersessions_superseded_circular_id'), table_name='supersessions')
    op.drop_index('ix_supersessions_superseded', table_name='supersessions')
    op.drop_index(op.f('ix_supersessions_resolved'), table_name='supersessions')
    op.drop_index(op.f('ix_supersessions_effective_date'), table_name='supersessions')
    op.drop_table('supersessions')
    op.drop_index(op.f('ix_obligations_paragraph_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_circular_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_citations_resolved'), table_name='citations')
    op.drop_index(op.f('ix_citations_normalised_reference'), table_name='citations')
    op.drop_index(op.f('ix_citations_citing_paragraph_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_citing_circular_id'), table_name='citations')
    op.drop_index('ix_citations_cited', table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_assessment_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_policy_clauses_tsv', table_name='policy_clauses', postgresql_using='gin')
    op.drop_index(op.f('ix_policy_clauses_policy_pack_id'), table_name='policy_clauses')
    op.drop_index('ix_policy_clauses_embedding_hnsw', table_name='policy_clauses', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('policy_clauses')
    op.drop_index('ix_paragraphs_circular_order', table_name='paragraphs')
    op.drop_index(op.f('ix_paragraphs_circular_id'), table_name='paragraphs')
    op.drop_table('paragraphs')
    op.drop_index('ix_eval_results_metric', table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_circular_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_run_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_policy_pack_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_circular_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('policy_packs')
    op.drop_index('ix_eval_runs_suite_started', table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_suite'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_run_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_git_sha'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_circulars_issue_date'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_doc_type'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_department'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_circular_number'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_checksum'), table_name='circulars')
    op.drop_table('circulars')
    # ### end Alembic commands ###

    # Autogenerate does not drop implicitly-created enum types; without this a
    # downgrade/upgrade cycle fails with "type already exists".
    for enum_name in (
        'extraction_method',
        'resolution_method',
        'supersession_type',
        'impact_type',
        'assessment_status',
        'step_status',
        'analyst_decision',
        'eval_suite',
        'retrieval_mode',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
